--- 
abstract: ~
author: 
  - Tokuhiro Matsuno and Mobirc AUTHORS.
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: gpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: mobirc
no_index: 
  directory: 
    - inc
    - t
recommends: 
  HTTP::MobileAgent::Plugin::Locator: 0
  Template::Plugin::HTMLMobileJp: 0
requires: 
  CGI: 0
  CGI::Cookie: 0
  CSS::Tiny: 0
  Carp: 0
  Class::Accessor: 0
  Encode: 0
  Encode::JP::Mobile: 0
  Exporter: 0
  File::Spec: 0
  FindBin: 0
  HTML::Entities: 0
  HTML::Entities::ConvertPictogramMobileJp: 0
  HTTP::MobileAgent: 0
  HTTP::MobileAgent::Plugin::Charset: 0
  HTTP::Response: 0
  Kwalify: 0
  List::MoreUtils: 0
  List::Util: 0
  POE: 0
  POE::Component::IRC: 0
  POE::Component::Server::TCP: 0
  POE::Filter::HTTPD: 0
  POE::Sugar::Args: 0
  Proc::Daemon: 0
  Scalar::Util: 0
  Storable: 0
  Template: 2.16
  Template::Provider::Encoding: 0
  UNIVERSAL::require: 0
  URI::Escape: 0
  URI::Find: 0
  YAML: 0
  perl: 5.8.0
tests: t/*.t t/*/*.t t/*/*/*.t
version: 0.04
