---
abstract: ~
author:
  - 'Tokuhiro Matsuno and Mobirc AUTHORS.'
build_requires:
  Sub::Uplevel: 0
  Test::Exception: 0
  Test::More: 0
  Text::Diff: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: mobirc
no_index:
  directory:
    - inc
    - t
recommends:
  Glib: 0.4
  POE::Loop::Glib: 0.0034
  POE::Session::Irssi: 0.4
requires:
  CSS::Tiny: 1.15
  Exporter: 5.62
  HTML::Entities: 1.35
  HTML::StickyQuery: 0.12
  HTML::StickyQuery::DoCoMoGUID: 0.01
  HTTP::Engine: 0.0.21
  HTTP::MobileAttribute: 0.07
  HTTP::Session: 0.26
  HTTPx::Dispatcher: 0.04
  JSON: 2.09
  List::MoreUtils: 0.22
  MIME::Base64::URLSafe: 0.01
  Module::Find: 0.06
  Mouse: 0.13
  POE: 1.003
  POE::Component::IRC: 5.88
  POE::Sugar::Args: 1.3
  Params::Validate: 0.91
  Path::Class: 0.16
  String::CamelCase: 0.01
  String::IRC: 0.01
  Text::MicroTemplate: 0.05
  UNIVERSAL::require: 0.11
  URI: 1.36
  URI::Find: 0.16
  YAML: 0.66
  perl: 5.8.0
version: 1.08_02
